name: Boo
favicon: null
layout_spectrum: 0.82178
typography_spectrum: 0.30198
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Family, Adventures, and sharing Jesus'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f48a3e'
    - '#000000'
    - '#ffffff'
    - '#424242'
    - '#737373'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
